// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // DIRECT_URL bypasses connection pooling for migrations
    // In Prisma 7, this is passed via CLI flag: npx prisma migrate dev --direct-url=$DIRECT_URL
    // Or configured here when supported by version
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
